#!/bin/bash
#SBATCH --job-name=train_01         # name for your job
#SBATCH --partition=gpu           # partition to run in
#SBATCH --nodes=1                   # node count
#SBATCH --ntasks=1                  # total number of tasks across all nodes
#SBATCH --ntasks-per-node=16        # total number of tasks across all nodes<
#SBATCH --time=24:00:00             # total run time limit (HH:MM:SS)
#SBATCH --output=$HOME/cluster/cluster_%j.%x.out  # where to save the output ( %j = JobID, %x = scriptname)
#SBATCH --error=$HOME/cluster/slurm.%j.err       # where to save error messages ( %j = JobID)
#SBATCH --gres gpu:1              # Generic resource required (1/2/4)


#Optional parameters
##SBATCH --mem=100	                # 100 MB RAM per allocated CPU
#SBATCH --mail-type=ALL             # send all email
#SBATCH --mail-user=$EMAIL          # email address from environemnt variable $EMAIL


echo "Unloading modules `hostname`"

# Purge modules to get a pristine environment:
module purge

# Make conda available:
eval "$(conda shell.bash hook)"

# Activate a conda environment:
conda activate dl23


echo "JobID is $SLURM_JOBID"
echo "Working directory is $SLURM_SUBMIT_DIR"
echo "Running python script `hostname`"

# Run a python script:
python main.py configs/default.json
