# ------------------------------------------------------------------------
# Description: Configuration file for the project
# Author: Amir Thapa Magar
# Email: amir.thapamagar(at)student.uni-siegen.de
# ------------------------------------------------------------------------

# Global variables

# Debugging options
debug: False

# Machine
machine: 'local' #'cluster'

# Global variables
global:
  - &window_size 150
  - &num_epochs 200
  - &num_classes 3
  - &sensors 'both' #'acc' # 'gyro' # 'both'
  - &device 'cuda'
  - &num_workers 4
  
# Model architecture parameters
architecture:
  name: 'deepconvlstm'
  sensors: *sensors
  window_size: *window_size
  device: *device

  # For CNN
  input_channels: 1
  hidden_channels: [64, 128, 256, 256]
  kernel_sizes: [1, 2, 3, 3, 5] # For Input layer and hidden layers
  cnn_bias: False

  # For LSTM
  lstm_hidden_size: 128
  lstm_num_layers: 2
  lstm_bias: False
  lstm_dropout: 0.25
  lstm_bidirectional: False

  # For Dropout Layer
  dropout: 0.25
  
  # For FC layer
  fc_hidden_size: 128
  num_classes: *num_classes
  activation: 'relu'

# Optimizer Hyperparameters
optim:
  name: 'adam'
  learning_rate: 0.001
  weight_decay: 0.0
  momentum: 0.9
  nesterov: True

# Loss function parameters
criterion:
  name: 'cross_entropy'
  weighted: True
  reduction: 'mean'

# LR Scheduler parameters
lr_scheduler:
  name: 'step_lr'
  step_size: 30
  gamma: 0.1

# Training Hyperparameters
train:
  device: *device
  num_epochs: *num_epochs
  batch_size: 256
  cross_validation: 'loso'
  
# Dataset parameters
dataset:
  folder: "OCDetect_Export" #'test' #'features' #""
  sensor: *sensors #'acc' # 'gyro' # 'both'
  overlapping_ratio: 0.0
  window_size: *window_size
  num_classes: *num_classes
  train_ratio: 0.9  # Highest 0.9
  split: 'subject_wise' # To:do future
  personalization: False
  personalized_subject: 3
  random_seed: 77
  shuffle: False
  num_workers: *num_workers
  pin_memory: False
  scaler_type: "MinMax" # "Standard" # "Robust"

# Filter parameters
filter:
  fc_low: 0.3
  fc_high: 18.0
  order: 5
  sampling_rate: 50.0 # Hz

# Metrics parameters
metrics:
  zero_division: 0.0 #"warn"  #'nan' #'warn'#0 # 1
  
