# ------------------------------------------------------------------------
# Description: Configuration file for the project
# Author: Amir Thapa Magar
# Email: amir.thapamagar(at)student.uni-siegen.de
# ------------------------------------------------------------------------

# Global variables

# Debugging options
debug: True

# Machine
machine: 'local' #'local' #'cluster'

# Global variables
global:
  - &window_size 150
  - &num_epochs 3
  - &num_classes 3
  - &sensors 'both' #'acc' # 'gyro' # 'both'
  - &device 'cuda'
  - &num_workers 4
  - &random_seed 55
  - &use_warn_metrics True
  
# Model architecture parameters
architecture:
  name: 'deepconvlstm'
  sensors: *sensors
  window_size: *window_size
  device: *device

  # For CNN
  input_channels: 1
  hidden_channels: [64, 64, 64, 64]
  kernel_sizes: [1, 3, 3, 5] 
  cnn_bias: False

  # For LSTM
  lstm_hidden_size: 128
  lstm_num_layers: 2
  lstm_bias: False
  lstm_dropout: 0.0
  lstm_bidirectional: False

  # For Dropout Layer
  dropout: 0.5
  
  # For FC layer
  fc_hidden_size: 128
  num_classes: *num_classes
  activation:
    name: 'elu' #'leaky_relu' #'relu' #'tanh' #'sigmoid' #'elu'
    negative_slope: 0.01 # For leaky_relu
    alpha: 1.0 # For elu

  # For weights initialization
  scheme: 'xavier_uniform'

# Optimizer Hyperparameters
optim:
  name: 'sgd'
  learning_rate: 0.001
  weight_decay: 0.0
  momentum: 0.9
  nesterov: True

# Loss function parameters
criterion:
  name: 'cross_entropy'
  weighted: False
  reduction: 'mean'

# LR Scheduler parameters
lr_scheduler:
  name: 'reduce_lr_on_plateau' #'step_lr' #'reduce_lr_on_plateau'
  step_size: 10 # For step_lr
  gamma: 0.1 # For step_lr
  factor: 0.02 
  patience: 10 # For reduce_lr_on_plateau
  mode: 'min' # For reduce_lr_on_plateau
  verbose: True 
  threshold: 0.0001 # For reduce_lr_on_plateau

# Training Hyperparameters
train:
  device: *device
  num_epochs: *num_epochs
  batch_size: 32
  cross_validation:
    name: 'kfold' #'losocv'
    k_folds: 2
    
# Dataset parameters
dataset:
  name: 'test_' #'datasets' #'OCDetect_Export' #'test' #'features' #"processed"
  sensor: *sensors #'acc' # 'gyro' # 'both'
  overlapping_ratio: 0.0
  window_size: *window_size
  num_classes: *num_classes
  train_ratio: 0.8  # Highest 0.9
  split: 'subject_wise' # To:do future
  personalization: False
  personalized_subject: 3
  random_seed: *random_seed
  shuffle: False
  num_workers: *num_workers
  pin_memory: False
  scaler_type: "MinMax" # "Standard" # "Robust"

# Filter parameters
filter:
  fc_low: 0.3
  fc_high: 18.0
  order: 5
  sampling_rate: 50.0 # Hz

# Metrics parameters
metrics:
  zero_division: "warn"  #'nan' #'warn'#0 # 1
  use_warn_metrics: *use_warn_metrics
