# ------------------------------------------------------------------------
# Description: Configuration file for the project
# Author: Amir Thapa Magar
# Email: amir.thapamagar(at)student.uni-siegen.de
# ------------------------------------------------------------------------

# Group parameters by phase
train_subjects: [1, 5, 6, 7, 8, 9, 11, 12, 13, 14, 15]
debug: True
architecture:
  name: 'cnn'
  input_dim: 54
  hidden_dim: 256
  kernel_size: 1
  num_layers: 2
  hidden_size: 256
  dropout: 0.5
  bidirectional: True
  num_directions: 2
  num_classes: 3
  input_size: 3
  activation: 'relu'
optim:
  name: 'adam'
  learning_rate: 0.001
  weight_decay: 0.0
  momentum: 0.9
  nesterov: True
  lr_scheduler:
    name: 'step_lr'
    step_size: 10
    gamma: 0.1
criterion:
  name: 'cross_entropy'
  weighted: False
  reduction: 'mean'
lr_scheduler:
  name: 'step_lr'
  step_size: 10
  gamma: 0.1
train:
  device: 'cuda'
  num_epochs: 100
  learning_rate: 0.001
  weight_decay: 0.001
  batch_size: 256
  num_classes: 3
  num_layers: 2
  hidden_size: 256
  dropout: 0.5
  bidirectional: True
  num_directions: 2
  input_size: 3
  batch_first: True
  learning_rate: 0.001
dataset:
  cross_validation: 'loso'
  folder: 'test' #'features' #"OCDetect_Export" #'features'
  sensor: 'both' #'acc' # 'gyro' # 'both'
  overlapping_ratio: 0.0
  window_size: 150
  num_classes: 3
  train_ratio: 0.9  # Highest 0.9
  split: 'subject_wise' # To:do
  personalization: False
  personalized_subject: 3
  random_seed: 55
  shuffle: False
  num_workers: 4
  pin_memory: False
  scaler_type: "MinMax" # "Standard" # "Robust"
filter:
  fc_low: 0.3
  fc_high: 15.0
  order: 5
  sampling_rate: 50.0 # Hz
metrics:
  zero_division: 0.0 #"warn"  #'nan' #'warn'#0 # 1
  
